### ISSUE TITLE
If my string contains '<a class=someclass href=someurl>' it skips translation?

### ISSUE THREAD

**Issue by maggerbo** [bitjson/gulp-l10n#14]
Thank you for a great plugin.

I have problems with some of my translations being skipped. All my strings where the string contains "<a class='somclass' href='someurl'>yada</a> the translations just defaults to the original html.

Do you have any idea why this is happening? Can the class parameter not come before the href parameter, could this affect things?

Please let me know if you need more information.

I hope you can help. Thanks!

**Comment by maggerbo** [comment]
Sorry. It just escaped my html. It was supposed to say:
All my strings where the string contains an a href with a class:
`<a class='someclass' href='someurl'>link</a>`
it skips the translation. I have seemed to find that it is overtime there is a class in the a href inside the string, then it skips translation.

I would love your input. Thanks :)

**Comment by bitjson** [comment]
Hey @maggerbo, happy to help. Any chance you're able to provide a repo url or test case?

**Comment by maggerbo** [comment]
https://bitbucket.org/Aggerbo/smartplan-international - it's the features/translation branch.

To come around the problem I had to extract `<a>` tags as well. My problem with this is that my `<a>` tags are often inside  `<li>` tags, this means the translation extracts the same thing twice.

I have Hammer for Mac that creates the Build folder, and my Gulpfile.js then uses this Build folder to do the translation.

I really appreciate your help! Thanks!

**Comment by maggerbo** [comment]
A great example of this is in the contact.html. There is a string that says:

> Smartplan is free for the first 30 days, no credit card or contracts needed. This easy to use scheduling software is used every day around the world by bars, shops, security companies and many more. If you have any questions, feel free to contact us here.

This string isn't translated because of the `<a class="current" href="contact.html">here</a>` inside the string.

You can check it out inside the NO folder.

I hope this makes sense...

**Comment by maggerbo** [comment]
Hey @bitjson ,

Just wanted to check in to hear if you had the chance to have a look at this?

Please let me know if I'm unclear or if I can do anything! Any help is appreciated! :)

**Comment by bitjson** [comment]
Hi @maggerbo, sorry for silence. I just checked out the project to take a look – it seems like that string is being extracted for localization now (hash `01cf6033`)? Did you manage to figure out the issue?

If not, it would be great if we could boil the issue down to a single [test case for s18n](https://github.com/bitjson/s18n/tree/master/test). For quick testing, you might want to try the [s18n CLI example](https://github.com/bitjson/s18n#example). If you could paste an `original.html` and the relevant `extract` options here to reproduce, I can write a test and try to get it passing. Thanks!
