### ISSUE TITLE
s18n: missing required option `nativeLocale`

### ISSUE THREAD

**Issue by dirkluijk** [bitjson/gulp-l10n#15]
I got the following error:

```
Error: s18n: missing required option `nativeLocale`.
    at module.exports (...\node_modules\s18n\lib\localize.js:9:11)
    at DestroyableTransform.localizeFiles [as _transform] (...\node_modules\gulp-l10n\index.js:57:24)
```

My Gulpfile.js:

``` js
var gulp = require('gulp');
var l10n = require('gulp-l10n');

// Prior to localization, pipe your locales to the setLocales method

gulp.task('load-locales', function () {
    return gulp.src('locales/*.json')
        .pipe(l10n.setLocales());
});

// Files piped to the plugin are localized and cloned to a separate subdirectory
// for each locale. e.g.: 'index.html' > 'de/index.html'

gulp.task('localize', ['load-locales'], function () {
    return gulp.src('src/**/*.html')
        .pipe(l10n())
        .pipe(gulp.dest('dist'))
});

gulp.task('default', ['localize']);
```

Directory structure:
/dist
/locales/en.json
/src/index.html
/Gulpfile.js

Version: `^1.2.0`

**Comment by bitjson** [comment]
Happy to help – could you pipe the locales through [gulp-debug](https://www.npmjs.com/package/gulp-debug) after the gulp.src line? It would be good to confirm the `en` locale is being found.

Something like:

```
gulp.task('load-locales', function () {
    return gulp.src('locales/*.json')
        .pipe(debug());
        .pipe(l10n.setLocales());
});
```

Might be helpful to also `console.log(localeCaches[cacheId].locales[localeCaches[cacheId].native])` at `...\node_modules\gulp-l10n\index.js:57:24` to confirm it's made it that far.

**Comment by dirkluijk** [comment]
It looks like the locales are found:

```
[08:53:11] gulp-debug: locales\en-US.json
[08:53:11] gulp-debug: locales\en.json
[08:53:11] gulp-debug: locales\nl-NL.json
[08:53:11] gulp-debug: 3 items
```

But the console.log says `undefined`, so there it has gone wrong.

My localeCaches looks like:

``` js
{
  default: {
    native: 'en',
    locales: {
      'C:\Development\playground-angular\locales\en-US': {},
      'C:\Development\playground-angular\locales\en': {},
      'C:\Development\playground-angular\locales\nl-NL': { Foo: 'Bar' }
    }
  }
}
```

According to this, the evaluation `localeCaches[cacheId].locales[localeCaches[cacheId]]` makes no sense to me.

**Comment by bitjson** [comment]
Ah, it looks like the localCaches object isn't properly formed – there may be a Window's specific problem (I haven't tested on Windows myself). Maybe you can dig into it a bit?

Your `localeCaches` should look like:

``` js
{
  default: {
    native: 'en',
    locales: {
      'en-US': {},
      'en': {},
      'nl-NL': { Foo: 'Bar' }
    }
  }
}
```

The following would return the native locale object (currently `{}`):

``` js
console.log(localeCaches[cacheId].locales[localeCaches[cacheId].native])
```

Looking through the code, nothing really jumps out at me. Maybe you could track down the source of the full paths being used for the `cacheId`s?

**Comment by wangbagang** [comment]
Is this problem solved? I also encountered such a problem ！

**Comment by dirkluijk** [comment]
Not solved yet, I guess it's a Windows issue like bitjson says. I will try to take a look today.

**Comment by wangbagang** [comment]
this is my slove, in gulp-l10n\index.js
line113: var localeId = file.path.substr(file.base.length).split('/').pop().split('.').shift(); 
I has solved;

**Comment by bitjson** [comment]
Hey all, I'm sorry – I just realized that the most recent version of this repo had not been released to npm. (Thanks @wangbagang for the code snippet that alerted me.)

@teodors was kind enough to submit [a pull request](https://github.com/bitjson/gulp-l10n/pull/13) several months ago fixing this issue, but somehow I failed to release it to npm. I just released [v1.2.1](https://github.com/bitjson/gulp-l10n/releases/tag/v1.2.1), with the bug fix. Please let me know if this solves the issue!

**Comment by wangbagang** [comment]
Not solve my problem.the error is:
d:\workspace\it-web\node_modules\gulp-l10n\node_modules\s18n\lib\utils.js:5
    return string.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, '\\$1');
beacuse the "string" is JsonObject not string;

**Comment by keithrz** [comment]
I ran into this issue, too.  With no updates since February, it looks like this library is a lemon.  DO NOT WANT
