### ISSUE TITLE
Directive/attribute to cancel automatic translation of elements/attributes

### ISSUE THREAD

**Issue by bitjson** [bitjson/gulp-l10n#4]

**Comment by berstend** [comment]
+1

**Comment by bitjson** [comment]
Hi @berstend – this is now possible, please see the [`s18n` extract options](https://github.com/bitjson/s18n#extract-options) for more info. You can use [`cancelers`](https://github.com/bitjson/s18n#cancelers) to canceling translation of elements and an [`attributeCanceler`](https://github.com/bitjson/s18n#attributecanceler) for one-off canceling of attributes.

Please let me know if you have feedback or ideas for improvement!
